name          'evenup-yum'
version       '0.1.0'
source        'https://github.com/evenup/evenup-yum'
author        'evenup'
license       'Apache 2.0'
summary       'Manages installed repos through hiera'
description   ''
project_page  'https://github.com/evenup/evenup-yum'

dependency 'puppetlabs/stdlib'
