# This is an autogenerated function, ported from the original legacy version.
# It /should work/ as is, but will not have all the benefits of the modern
# function API. You should see the function docs to learn how to add function
# signatures for type safety and to document this function using puppet-strings.
#
# https://puppet.com/docs/puppet/latest/custom_functions_ruby.html
#
# ---- original file header ----
#
# hash_to_repo_file.rb
#

# ---- original file header ----
#
# @summary
#       Returns the filenames of yum repos to allow purging unused repos
#
#
Puppet::Functions.create_function(:'yum::hash_to_repo_file') do
  # @param arguments
  #   The original array of arguments. Port this to individually managed params
  #   to get the full benefit of the modern function API.
  #
  # @return [Data type]
  #   Describe what the function returns here
  #
  dispatch :default_impl do
    # Call the method named 'default_impl' when this is matched
    # Port this to match individual params for better type safety
    repeated_param 'Any', :arguments
  end


  def default_impl(*arguments)
    
    raise(Puppet::ParseError, "hash_to_repo_file(): Wrong number of arguments " +
      "given (#{arguments.size} for 1)") if arguments.size < 1

    repos = arguments[0]
    filenames = {}

    repos.each do |repo,value|
      filenames['/etc/yum.repos.d/' + repo + '.repo'] = {}
    end

    return filenames
  
  end
end
